version: 2.1

jobs:
  check_scapegoat:
    docker:
      - image: circleci/openjdk:11-jdk
    resource_class: medium
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run:
          name: Scapegoat check
          command: |
            sbt scapegoat
            length=$(wc -l "target/scala-2.13/scapegoat-report/scapegoat.html" | awk '{print $1}')
            if [[ $length -gt 66 ]]; then
              echo "There are Scapegoat errors" && exit 1;
            fi
  check_scalafmt:
    docker:
      - image: circleci/openjdk:11-jdk
    resource_class: medium
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run:
          name: Style check
          command: |
            sbt formatAll
            if [[ -n $(git diff --name-only) ]]; then
              echo "These files are not formatted correctly:" && git diff --name-only && exit 1;
            fi
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    resource_class: medium+
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: sbt compileAll

      - save_cache:
          paths:
            - ~/.ivy2
          key: v1-dependencies-{{ checksum "build.sbt" }}

      - run: sbt test

workflows:
  version: 2
  build_and_integration:
    jobs:
      - check_scapegoat
      - check_scalafmt
      - build
